[role="pagenumrestart"]
[[intro_what_is_the_lightning_network]]
== Вступ

Ласкаво просимо до Освоєння Lightning Network!

Lightning Network (Блискавична Мережа, скорочено LN) - це протокол для використання Біткоїна у розумний і неочевидний спосіб.
Ця технологія працює на другому рівні поверх Біткоїна.
Вона змінює спосіб, яким люди обмінуються цінностями онлайн і є одним із найбільш захоплюючих покращень, що трапилось в історії Біткоїна. 
Сьогодні, в 2020 році Lightning Network ще перебуває у дитячому віці.
Концепція була вперше запропонована в 2015, а перша імплементація з'явилась у 2018.
В 2020 ми лише починаємо роздивлятись можливості, які дає нам Lightning Network, серед них ми бачимо кращу конфіденційність, швидкість та здатність до масштабування.
Маючи розуміння основ Lightning Network, ви можете прийняти участь в формуванні майбутнього мережі, одночасно створюючи можливості і для себе. 
Для розуміння матеріалу потрібні деякі базові знання про Біткоїн, але їх легко здобути, прочитавши перші два розділи книги _Mastering Bitcoin_, яка доступна онлайн і безкоштовно.

Незважаючи на те, що більша частина цієї книги написана для програмістів, перші два розділи написані таким чином, щоб бути доступними кожному, незалежно від його технічного досвіду. Щоб краще зрозуміти, як ця технологія насправді працює, і чому люди її використовують, ми будемо стежити за кількома користувачами та їхніми історіями. Але спочатку ми представимо деякі ключові поняття в Lightning Network. Почнемо з того, для чого взагалі була запропонована Lightning Network.

=== Мотивація Lightning Network

По мірі розвитку мережі Біткоїн та зростання попиту на транзакції, збільшується кількість транзакцій в кожному блоці, поки вона врешті-решт не впирається в ліміт розміру блоку. 
Коли блоки заповнені повністю, транзакції, для яких не знайшлось місця в жодному блоці, залишаються чекати в черзі. 
Багато користувачів збільшують комісію, щоб заплатити за місце для своєї транзакції в наступному блоці. 
Разом із тим все більше користувачів залишаються пасти задніх. 
Їхні операції, наприклад мікротранзакції, повсякденні витрати на невеликі суми, не мають економічного сенсу для існування в мережі Біткоїн. 
Ми могли б просто збільшити розмір блоку, щоб створити місце для цих мілких транзакцій.
Але збільшення розміру блоку просто перекладає проблему на операторів нод, і вимагає від них збільшення витрат для обробки цих додаткових транзакцій.

Оскільки блокчейни - це gossip-протоколи (протоколи "пліток", де кожен учасник ділиться "плітками" з іншими випадково вибраними учасниками), кожна нода має знати та перевіряти кожну транзакцію, що трапляється в мережі. Крім цього, після перевірки кожна транзакція та кожний блок мають бути відправлені нодам-"сусідам", що примножує вимоги до пропускної здатності. Чим більший розмір блоку, тим більші вимоги до пропускної здатності, а також до ресурсів, потрібних для обробки та зберігання інформації для кожної окремої ноди. Таким чином, збільшення розміру блоку знижує ефективність масштабування. Більше того, такий підхід до масштабування має небажаний побічний ефект централізації мережі за рахунок зменшення кількості нод та їх операторів. Оскільки оператори нод не отримують компенсацій за працюючі ноди, то у разі, якщо утримання нод стане дуже витратним, лише кілька добре профінансованих операторів зможуть утримувати власні ноди.

[Примітка]
====
Обчислення демонструють, що збільшення розміру блоку або зменшення часу блоку мали б суттєвий побічний ефект у вигляді централізації мережі. 
Припустимо, що використання мережі Біткоїна досягло 40,000 транзакцій в секунду.
При середньому розмірі транзакції 250 Байт, це вимагає швидкості передачі данних 10 МБ/с або 80 Мбіт/с лише для скачування всіх транзакцій без урахування необхідності передачі всієї цієї інформації іншим пірам.

Хоча 10 МБ/с не здається чимось величезним в контексті високошвидкісної оптики та мобільних швидкостей 5G, але це фактично виключає можливість запустити власну ноду всім, хто не здатний задовільнити цю вимогу, особливо це стосується країн, де швидкістний Інтернет відсутній або не широко доступний.
Користувачі також мають інші потреби у використанні пропусної здатності і не варто чекати, що вони витрачатимуть її лише заради скачування транзакцій.
Більш того, для локального зберігання цієї інформації потрібно 864,000 Мегабайт на день. Це майже 1 Терабайт або 1 жосткий диск на день.
Верифікація 40,000 ECDSA підписів в секунду видається ледь досяжною (https://bitcoin.stackexchange.com/questions/95339/how-many-bitcoin-transactions-can-be-verified-per-second), ноди навряд чи зможуть коли-небудь синхронізувати блокчейн. 
====

А що, коли кожній ноді не потрібно було б знати і перевіряти кожну окрему транзакцію? Чи існує спосіб використовувати здатні до масштабування off-chain (поза блокчейном) транзакції без загрози безпеки для мережі Біткоїн?

У лютому 2015 Джозеф Пун і Тадеуш Дрейя запропонували можливе вирішення Проблеми Масштабування Біткоїна в свої роботі _"The Bitcoin Lightning Network: Scalable Off-Chain Instant Payments" ("Блискавична Мережа Біткоїна: Масштабовані Off-Chain Миттєві Платежі")_ footnote:[Joseph Poon, Thaddeus Dryja - "The Bitcoin Lightning Network:
Scalable Off-Chain Instant Payments" (https://lightning.network/lightning-network-paper.pdf).]. На той час Visa обробляла 47,000 транзакцій на секунду, Пун і Дрейя у своєму вайтпейпері оцінили, що для такого навантаження Біткоїну потрібно мати блоки розміром у 8 ГБ. Це зробило би утримання ноди досяжним тільки для великих підприємств і промисловості. У кінцевому підсумку лише кілька користувачів були б здатні верифікувати блокчейн, а це руйнує модель довіри до Біткоїна.

Lightning Network пропонує нову мережу, "другий рівень", на якому користувачі можуть здійснювати платежі один одному peer-to-peer, без необхідності публікувати окрему транзакцію в блокчейні Біткоїна на кожний окремий платіж.
Користувачі можуть платити один одному всередині Lightning Network будь-яку кількість разів, використовуючи блокчейн Біткоїна тільки для того, щоб завантажити біткоїни у Lightning Network і щоб їх звідти забрати.
В результаті більшість платежів можуть виконуватись поза блокчейном, і лише 2 транзакції - початкова для завантаження біткойнів і кінцева для їх виведення - мають бути оброблені Біткоїн-нодами.
Окрім зменшення навантаження на ноди, платежі в Lightning Network будуть дешевшими для користувачів, оскільки їм не буде треба платити комісію за розміщення платежів у блокчейні Біткоїна. Також платежі будуть більш приватними, оскільки вони не публікуються на всю мережу і навіть не потребують постійного зберігання.

Хоча Lightning Network була придумана для Біткоїна, вона може бути реалізована на будь-якому блокчейні, що відповідає її технічним вимогам.

=== Основні Поняття Lightning Network

Починаючи вивчення Lightning Network, ми зіткнемося з деякими технічними термінами, які спочатку можуть заплутати і можуть бути трохи важкими для розуміння. Незважаючи на те, що всі ці поняття та терміни мають визначення у глосарії і будуть детально пояснені по мірі проходження книги, для початку нам потрібні деякі основні роз’яснення. Ось деякі поняття, з якими ви зустрінетесь у перших двох главах цієї книги:

Нода:: Комп'ютер-учасник мережі. Lightning-нода - комп'ютер, що бере участь у Lightning Network. Біткоїн-нода - комп'ютер, що бере участь у мережі Біткоїн. Зазвичай користувач Lightning Network має Lightning-ноду та Біткоїн-ноду.

Блокчейн:: Розподілена книга транзакцій, що створюється мережею комп'ютерів. Біткоїн, наприклад, це система що створює блокчейн. Lightning Network не є блокчейном і не створює блокчейн. Це мережа, яка покладається на існуючий зовні блокчейн задля власної безпеки.

Транзакція:: Структура даних, яка фіксує передачу управління над деякими коштами (наприклад, деякими біткойнами). Lightning Network покладається на Біткоїн-транзакції (або транзакції іншого блокчейну) для відстеження контролю над коштами.

Платіж:: Коли обмін цінностями здійснюється в Lightning Network, ми називаємо це платежем, оскільки термін Транзакція є технічним терміном для записів у Біткоїн-блокчейні.

Платіжний Канал:: _Фінансові відносини_ між двома нодами Lightning Network, як правило, реалізовані мульти-підписними Біткоїн-транзакціями, що ділять контроль над біткоїнами між двома Lightning-нодами.

On-Chain і Off-Chain:: Платіж є "on-chain", якщо він записаний у вигляді транзакції у блокчейні Біткоїна (або іншого блокчейна). Платежі, відправлені через платіжні канали між Lightning-нодами, які не відображаються у блокчейні, називаються "off-chain" платежами.

Більш детальне визначення цих та багатьох інших термінів можна знайти в <<глосарій>>. У цій книзі ми пояснимо, що означають ці поняття і як власне працюють ці технології.

[Порада]
====
У цій книзі ви зустрінете слово "Біткоїн" з великої літери, воно означає _Систему Біткоїн_ і є власним іменником. Ви також зустрінете "біткойн" з маленької літери _б_, це означає одиницю валюти.
====

=== Що таке Lightning Network?

Lightning Network - це мережа, що працює в якості протоколу "другого рівня" поверх Біткоїна та інших блокчейнів. Lightning Network дозволяє здійснювати швидкі, безпечні, приватні, не потребуючі довіри та дозволу платежі. Деякі особливості Lightning Network:

 * Користувачі Lightning Network можуть відправляти платежі один одному дешево і в реальному часі.
 * Користувачі Lightning Network при здійсненні платежів не повинні чекати підтвердження блоків.
 * Як тільки платіж у Lightning Network був здійснений (зазвичай протягом кількох секунд), він є остаточним і не може бути скасованим. Як і у випадку з Біткоїн-транзакціями, лише одержувач може повернути платіж у Lightning Network.
 * В той час, як "on-chain" Біткоїн-транзакції транслюються на всю мережу і перевіряються всіми нодами в мережі, платежі що маршрутизуються через Lightning Network, передаються між парами нод і невидимі для інших учасників, що підвищує приватність.
 * На відміну від мережі Біткоїн, платежі що маршрутизуються через Lightning Network, не потребують постійного зберігання. Lightning Network використовує менше ресурсів, а отже є дешевшою. Ця властивість також надає переваги щодо приватності.
 * Lightning Network використовує цибульну маршрутизацію (onion routing) подібно до протоколу, що використовується мережею The Onion Router (TOR). Тому навіть ноди, що беруть участь у маршрутизації платежу, знають лише своїх безпосередніх попередника та наступника в маршруті платежа.

[[user-stories]]
=== Приклади Використання, Користувачі та Їх Історії

Як система електронної готівки, Біткоїн зберігає три найважливіші властивості грошей (засіб обміну, засіб заощадження та одиниця обліку). Інші релевантні властивості систем цифрових платежів включають можливість третіх сторон використовувати їх в якості способу контроля і/або інструменту спостереження.
Гроші (і зокрема Біткоїн) було винайдено для спрощення торгівлі і забезпечення обміну цінностями між людьми. Однак без Lightning Network (або іншого рішення другого рівня для масштабування), було б неможливо одночасно використовувати Біткоїн як засіб обміну, оскільки сама мережа стала б перевантаженою, повільною та дорогою.

На сьогоднішній день Біткоїн - це найдовше працююча, найбезпечніша криптовалюта або система електронної готівки. Багато людей вважають, що Біткоїн є найбільш стабільним засобом заощадження з усіх існуючих криптовалют. Lightning Network дозволяє людям надсилати та отримувати біткойни без накладних витрат, пов’язаних з on-chain транзакціями. Спочатку це може здатися заплутаним. Можливо, вам цікаво, як Lightning Network насправді цього досягає? Ми могли б пояснити це у термінах інформатики, але набагато легше буде зрозуміти, якщо подивитись з точки зору користувачів. У наших прикладах деякі люди вже використовували Біткоїн, а інші є новачками. Кожна із перелічених історій, ілюструє один або декілька конкретних прикладів використання. У цій книзі ми будемо розглядати такі історії:

споживач::
Аліса - користувачка Біткоїна, яка хоче здійснювати швидкі, безпечні, дешеві та приватні платежі за невеликі роздрібні покупки. Вона купує каву за біткоїни, використовуючи Lightning Network.

продавець::
Боб володіє кав'ярнею "Кафе Боба". "On-chain" біткойн-платежі не масштабуються на такі маленькі суми, як ціна чашки кави, тому Боб використовує Lightning Network, щоб приймати біткойн-платежі майже миттєво і сплачуючи малу комісію.

веб-дизайнер::
Саанві - веб-дизайнерка та розробник в Бангалорі, Індія. Вона приймає біткойни за свою роботу, але бажає отримувати зарплату частіше, і тому використовує Lightning Network, щоб отримувати поступові виплати за кожний невеликий виконаний етап роботи. За допомогою Lightning Network вона може виконувати більше дрібних робіт для більшої кількості клієнтів, не турбуючись про комісії та затримки.

створювач контенту::
Джон - 9-річний хлопчик з Нової Зеландії, який хотів ігрову приставку, як у його друзів. Однак тато сказав йому, що для того, щоб її придбати, він повинен сам заробити гроші. Зараз Джон - художник-початківець, тому він знає, що поки він ще вдосконалюється, він не може багато брати за свої роботи. Дізнавшись про Біткоїн, йому вдалося створити веб-сайт для продажу своїх малюнків через Інтернет. Використовуючи Lightning Network, Джон має можливість приймати в оплату 1 долар за малюнок, що зазвичай вважалось мікроплатежем, і було неможливо виконати через інші методи оплати. Крім того, використовуючи світову валюту, таку як біткойн, Джон зміг продати свої твори мистецтва клієнтам у всьому світі і, врешті-решт, придбати ігрову консоль, яку він так відчайдушно бажав.

геймер::
Глорія - підлітковий геймер з Філіппін. Вона грає в безліч різних комп’ютерних ігор, але її улюбленими є ті, що мають «внутрішньоігрову економіку», засновану на реальних грошах. Граючи в ігри, вона також заробляє гроші, купуючи та продаючи віртуальні ігрові предмети. Lightning Network дозволяє їй здійснювати транзакції на невеликі суми для придбання ігрових предметів, а також заробляти невеликі кошти за виконання квестів.

мігрант::
Фарел - іммігрант, який працює на Близькому Сході і відправляє гроші додому своїй родині в Індонезію. Грошові перекази та банки беруть високі комісії, а Фарел бажає часто відправляти невеликі суми. Використовуючи Lightning Network, Фарел може відправляти біткойни з будь-якою частотою та із незначними комісіями.

софт як сервіс::
Вей - підприємець, який надає інформаційні послуги, пов’язані з Lightning Network, а також з Біткоїном та іншими криптовалютвами. Вей монетизує доступ до свого API через мікроплатежами в Lightning Network. Додатково, Вей виконує роль постачальника ліквідності, надаючи в оренду вхідну спроможність платіжного каналу в Lightning Network, стягуючи невелику плату за кожен період оренди.

=== Підсумок Глави

У цій главі ми розглянули історію Lightning Network та мотивації, що стоять за рішеннями другого рівня щодо масштабування Біткоїна та інших блокчейн-систем. Ми вивчили базові терміни - нода, платіжний канал,  on-chain та off-chain транзакції. Нарешті, ми зустріли Алісу, Боба, Саанві, Джона, Глорію, Фарела та Вей, за якими будемо стежити впродовж решти книги. У наступному розділі ми познайомимося з Алісою та прослідкуємо за її думкою, коли вона обирає Lightning-гаманець та готується зробити свій перший Lightning-платіж, щоб придбати чашку кави в Кафе Боба.